name: Generate Dependabot Configuration

on:
  pull_request:
    paths:
      - '**/*'

jobs:
  run_python_script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.12.2

      - name: Run config generation script
        run: |
          wget https://raw.githubusercontent.com/chmrad/prow-infra/main/tools/generate_dependabot.py
          python generate_dependabot.py
          mv dependabot.yml .github/
          git branch -a
          
      - name: Commit change
        uses: EndBug/add-and-commit@v9
        with:
          default_author: github_actions
