name: Generate Dependabot Configuration

on:
  pull_request:
    paths:
      - '**/*'

jobs:
  run_python_script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.12.2

      - name: Pull PR
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: gh pr checkout ${{ github.event.pull_request.number }}
        
      - name: Run config generation script
        run: |
          wget https://raw.githubusercontent.com/chmrad/prow-infra/main/tools/generate_dependabot.py -O /tmp/generate_dependabot.py
          python /tmp/generate_dependabot.py
          mv dependabot.yml .github/
          git branch -a
          git status
          
      - name: Commit change
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor }}@users.noreply.github.com"
          git add .github/dependabot.yml
          git diff --quiet || git commit -m "Regenerating Dependabot config"
          git push origin ${{ github.head_ref }}
